#!/bin/bash
#
WPASUPP=/usr/sbin/wpa_supplicant_uwin
WPACLI=/usr/sbin/wpa_cli_uwin
HOSTAPD=/usr/sbin/hostapd_uwin
BTTNODE=/usr/sbin/bttnode_uwin
IWUTILS=/sbin/iw
DHCPCLI=/sbin/dhclient
DHCPSRV=/usr/sbin/dhcpd
DNSMASQ=/usr/sbin/dnsmasq
RESCONF=/etc/resolv.conf

#####################################################
# Ethernet Device
WIRE_ETH=enp0s25

# WiFi PCI Module
IWL_MOD=iwldvm

# WiFi PCI Device
WIFI_PCI=wlp3s0

# WiFi USB Module
RTL_MOD=88x2bu

# WiFi USB Device
WIFI_USB=wlxd45d649cfe2d

#####################################################
# WAN Bridge Interface
BRI_IF=br-wan

# LAN Bridge Interface
LAN_IF=br-lan

# ETH Primary Interface
ETH_IF=$WIRE_ETH

# USB Secondary Interface
#USB_IF=enx3c18a041d23a

# ENX Secondary Interface
#ENX_IF=enx0050b620f531

# WiFi WAN Interface
STA_IF=$WIFI_PCI

# WiFi Monitor Interface
#MON_IF=mon0

# WiFi Extra WAN Interface
#STX_IF=$WIFI_USB

# WiFi Extra LAN Interface
WLX_IF=$WIFI_USB

#####################################################
# 0: BTT COUNT - Disabled
# #: BTT COUNT - Valid # (2, 4, 8, or 16)
BTT_COUNT=0
BTT_LOCAL=4

BTT_NET=192.168.108.0/24
BTT_DHCP_LEASE=/var/lib/dhcp/dnsmasq.leases

#####################################################
# 0: Bridge PHY - NONE
# 1: Bridge PHY - WIRE ETH
# 2: Bridge PHY - WIFI PCI
BRI_PHY=1

# 0: Bridge Mode Static
# 1: Bridge Mode Client
BRI_MODE=1

BRI_ALIVE=0
BRI_ALIVE_IP=192.168.112.30

BRI_PING=0
BRI_PING_IP=8.8.8.8

BRI_GW=192.168.112.1
BRI_IP=192.168.112.3/24
BRI_BRD=192.168.112.255

BRI_DHCP_PID=/var/run/dhclient-${BRI_IF}.pid
BRI_DHCP_LEASE=/var/lib/dhcp/dhclient-${BRI_IF}.lease

#####################################################
# 0: ETH Mode - Static
# 1: ETH Mode - Client
# 2: ETH Mode - Server
# 3: ETH Mode - Bridge
ETH_MODE=1

# 0: Master VLAN Disabled
# 1: Master VLAN Enabled
ETH_VLAN=0

ETH_ALIVE=0
ETH_ALIVE_IP=192.168.112.30

ETH_PING=0
ETH_PING_IP=8.8.8.8

ETH_GW=192.168.112.1
ETH_IP=192.168.112.3/24
ETH_BRD=192.168.112.255

ETH_DHCP_PID=/var/run/dhclient-${ETH_IF}.pid
ETH_DHCP_LEASE=/var/lib/dhcp/dhclient-${ETH_IF}.lease

#####################################################
# 0: USB Mode - Static
# 1: USB Mode - Client
# 2: USB Mode - Server
# 3: USB Mode - Bridge
USB_MODE=1

# 0: Slave VLAN Disabled
# 1: Slave VLAN Enabled
USB_VLAN=0
USB_VLAN_ID=500

USB_ALIVE=0
USB_ALIVE_IP=192.168.112.30

USB_PING=0
USB_PING_IP=8.8.8.8

USB_GW=192.168.0.1
USB_IP=192.168.0.100/24
USB_BRD=192.168.0.255

USB_DHCP_PID=/var/run/dhclient-${USB_IF}.pid
USB_DHCP_LEASE=/var/lib/dhcp/dhclient-${USB_IF}.lease

#####################################################
# 0: ENX Mode - Static
# 1: ENX Mode - Client
# 2: ENX Mode - Server
# 3: ENX Mode - Bridge
ENX_MODE=1

# 0: Slave VLAN Disabled
# 1: Slave VLAN Enabled
ENX_VLAN=0
ENX_VLAN_ID=400

ENX_ALIVE=0
ENX_ALIVE_IP=192.168.112.30

ENX_PING=0
ENX_PING_IP=8.8.8.8

ENX_GW=192.168.1.1
ENX_IP=192.168.1.100/24
ENX_BRD=192.168.1.255

ENX_DHCP_PID=/var/run/dhclient-${ENX_IF}.pid
ENX_DHCP_LEASE=/var/lib/dhcp/dhclient-${ENX_IF}.lease

#####################################################
# 0: MON WiFi USB Disabled
# 1: MON WiFi USB Enable
MON_USB=0
MON_USB_CHAN=149

#####################################################
# 0: STX Mode - Static
# 1: STX Mode - Client
STX_MODE=1

STX_ALIVE=0
STX_ALIVE_IP=192.168.112.30

STX_PING=0
STX_PING_IP=8.8.8.8

STX_GW=192.168.112.1
STX_IP=192.168.112.3/26
STX_BRD=192.168.112.255

STX_DBG=2
STX_ACL=0
STX_AUTO_ROAM=2
STX_RSSI_STEP=10

STX_CTRL=/var/run/wpa_supplicant-${STX_IF}/
STX_PID=/var/run/wpa_supplicant-${STX_IF}.pid
STX_LOG=/var/log/wpa_supplicant-${STX_IF}.log
STX_CONF=/etc/conf/wpa_supplicant-${STX_IF}.conf

STX_DHCP_PID=/var/run/dhclient-${STX_IF}.pid
STX_DHCP_LEASE=/var/lib/dhcp/dhclient-${STX_IF}.lease

#####################################################
# 0: WAN Bridge Disabled
# 1: WAN Bridge Enabled
WLX_WAN=1

WLX_DBG=2
WLX_POWER_TX=0

WLX_TOGGLE_TEST=0
WLX_TOGGLE_ON=60
WLX_TOGGLE_OFF=60
WLX_SWING_TEST=0
WLX_SWING_DWELL=15
WLX_SWING_HIGH=2500
WLX_SWING_STEP=300
WLX_SWING_LOW=100

WLX_CTRL=/var/run/hostapd-${WLX_IF}/
WLX_PID=/var/run/hostapd-${WLX_IF}.pid
WLX_LOG=/var/log/hostapd-${WLX_IF}.log
WLX_CONF=/etc/conf/hostapd-${WLX_IF}.conf

#####################################################
# 0: MON WiFi PCI Disabled
# 1: MON WiFi PCI Enable
MON_PCI=0
MON_PCI_CHAN=8

#####################################################
# 0: STA Mode - Static
# 1: STA Mode - Client
STA_MODE=1

STA_ALIVE=0
STA_ALIVE_IP=192.168.112.30

STA_PING=0
STA_PING_IP=8.8.8.8

STA_GW=192.168.112.1
STA_IP=192.168.112.3/24
STA_BRD=192.168.112.255

STA_DBG=2
STA_ACL=0
STA_AUTO_ROAM=2
STA_RSSI_STEP=6

STA_CTRL=/var/run/wpa_supplicant-${STA_IF}/
STA_PID=/var/run/wpa_supplicant-${STA_IF}.pid
STA_LOG=/var/log/wpa_supplicant-${STA_IF}.log
STA_CONF=/etc/conf/wpa_supplicant-${STA_IF}.conf

STA_DHCP_PID=/var/run/dhclient-${STA_IF}.pid
STA_DHCP_LEASE=/var/lib/dhcp/dhclient-${STA_IF}.lease

#####################################################
LAN_IP=192.168.112.193/26
LAN_GW=192.168.112.193
LAN_BRD=192.168.112.255
LAN_NET=192.168.112.192/26
LAN_MASK=255.255.255.192
LAN_START=192.168.112.195
LAN_END=192.168.112.254

LAN_DHCP_CONF=/etc/dhcp/dhcpd.conf
LAN_DHCP_LEASE=/var/lib/dhcp/dhcpd.leases

#####################################################
OPT_DIR=/opt/uwin/

WAN_INFO=${OPT_DIR}/network-wan.info
LAN_INFO=${OPT_DIR}/network-lan.info

STA_INFO=${OPT_DIR}/wireless-sta.info
STX_INFO=${OPT_DIR}/wireless-stx.info
WLX_INFO=${OPT_DIR}/wireless-wlx.info
PHY_INFO=${OPT_DIR}/wireless-phy.info
BTT_INFO=${OPT_DIR}/wireless-btt.info
